apiVersion: v1
kind: Service
metadata:
  name: {{ include "cartservice.fullname" . }}
  labels: {{- include "cartservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: grpc
  selector: {{- include "cartservice.selectorLabels" . | nindent 4 }}
